### Clean and conventional Energies in Mexico

#### In this project we'll examine how has been the implementation of clean energy from the plan of 2021 to 2024

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import statsmodels.api as sm
sb.set()

### Load the data

In [18]:
data_generation_2024 = pd.read_csv("Generación de energía eléctrica 2021-2024 GigaWattsh.csv") #GigaWatts per hour
data_generation_2024

                     Tecnologia    2021    2022    2023    2024
0                  Convencional  241340  239658  243491  243551
1               Ciclo combinado  183344  186126  191721  189770
2   Termoelectrica convencional   12377   10720    9534    9293
3                Carboelectrica   35450   35450   35450   35529
4                      Turbogas    4032    1356    1241     238
5            Combustion Interna    2311    2181    1719    1494
6              Lecho fluidizado    3825    3825    3825    7227
7                        Limpia  104040  116843  124162  135746
8                     Renovable   76712   88270   92823  102225
9                Hidroelectrica   32334   32334   32334   34433
10                       Eolica   26390   36134   40180   46899
11                   Geotermica    6403    6306    6036    6324
12           Solar fotovoltaica   11561   13472   13978   14544
13                   Termosolar      24      24      24      24
14                        Otras   27328   28573   31339   33521
15              Nucleoelectrica   10931   10931   10931   10961
16                   Bioenergia    4500    6103    8162    9257
17       Cogeneracion eficiente  118897   11539   12246   13304
18                        Total  345380  356502  367653  379297

### Energy generation for 2021-2024

In [19]:
cleanTech_generation = data_generation_2024.copy()

In [20]:
cleanTech_generation = cleanTech_generation.iloc[7:19,:]
cleanTech_generation

                Tecnologia    2021    2022    2023    2024
7                   Limpia  104040  116843  124162  135746
8                Renovable   76712   88270   92823  102225
9           Hidroelectrica   32334   32334   32334   34433
10                  Eolica   26390   36134   40180   46899
11              Geotermica    6403    6306    6036    6324
12      Solar fotovoltaica   11561   13472   13978   14544
13              Termosolar      24      24      24      24
14                   Otras   27328   28573   31339   33521
15         Nucleoelectrica   10931   10931   10931   10961
16              Bioenergia    4500    6103    8162    9257
17  Cogeneracion eficiente  118897   11539   12246   13304
18                   Total  345380  356502  367653  379297

In [22]:
cleanTech_generation["+5%"] = [round((int(generation) * 40) / 35,2) for generation in list(cleanTech_generation["2024"])] #This calculates the total energy capacity for 40%
def additionalEnergy(actualGeneration, expectedGeneration):
    values = []
    for index,actual in enumerate(actualGeneration):
        difference = expectedGeneration[index] - actual
        values.append(difference)
    return values
additionalEnergy = additionalEnergy(cleanTech_generation["2024"].tolist(), cleanTech_generation["+5%"].tolist())
cleanTech_generation["Additional Generation (GW-h)"] = additionalEnergy
cleanTech_generation

,Tecnologia,2021,2022,2023,2024,+5%,Additional Generation (GW-h)
7,Limpia,104040,116843,124162,135746,155138.29,19392.29
8,Renovable,76712,88270,92823,102225,116828.57,14603.57
9,Hidroelectrica,32334,32334,32334,34433,39352.00,4919.00
10,Eolica,26390,36134,40180,46899,53598.86,6699.86
11,Geotermica,6403,6306,6036,6324,7227.43,903.43
12,Solar fotovoltaica,11561,13472,13978,14544,16621.71,2077.71
13,Termosolar,24,24,24,24,27.43,3.43
14,Otras,27328,28573,31339,33521,38309.71,4788.71
15,Nucleoelectrica,10931,10931,10931,10961,12526.86,1565.86
16,Bioenergia,4500,6103,8162,9257,10579.43,1322.43
17,Cogeneracion eficiente,118897,11539,12246,13304,15204.57,1900.57
18,Total,345380,356502,367653,379297,433482.29,54185.29

In [25]:
print("To reach the goal of having 40% of our energy from sustainable resources we need more plants to produce a total of " + str(round(cleanTech_generation["Additional Generation (GW-h)"][18], 2)) + " GigaWatts per hour.")

To reach the goal of having 40% of our energy from sustainable resources we need more plants to produce a total of 54185.29 GigaWatts per hour.